### ISSUE TITLE
Try Darik's Malware

### ISSUE THREAD

**Issue by G9-dev-real** [pankoza-pl/gdithings#2]
Go to https://github.com/Darik2121/Made-by-me-Malwares and try Darik's Malwares pls

**Comment by pankoza-pl** [comment]
his github is deleted and you are just filling my mailbox with trash

**Comment by G9-dev-real** [comment]
No

**Comment by G9-dev-real** [comment]
> his github is deleted and you are just filling my mailbox with trash

His GitHub not deleted

**Comment by Darik8Coder** [comment]
> his github is deleted and you are just filling my mailbox with trash

his github is flagged*

**Comment by G9-dev-real** [comment]
Poo: https://github.com/poopoo
