### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by ghost** [pankoza-pl/gdithings#9]
Can you pls upload exe?
Bc i dont use C++

**Comment by pankoza2-pl** [comment]
skidder

**Comment by darik9pl** [comment]
IM NOT SKIDDER

**Comment by darik9pl** [comment]
> skidder

YOU ARE A SKIDDER MORE THAN ME

**Comment by darik9pl** [comment]
Just pls upload EXE files.
Please Because I don't know how to compile in C++.

**Comment by Sekai-Moeru** [comment]
ironic, isnt it.
